DiemDanhVanTay/DiemDanhVanTay/Models/TheTu.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace DiemDanhVanTay.Models
{
    public class TheTu
    {
        [Key]
        public int TheTuID { get; set; }

        [ForeignKey("NguoiDung")]
        [Display(Name = "Người dùng")]
        public int NguoiDungID { get; set; }

        [Display(Name = "Vân tay thứ nhất")]
        public string VanTay1 { get; set; }

        [Display(Name = "Vân tay thứ hai")]
        public string VanTay2 { get; set; }

        [Display(Name = "Vân tay thứ ba")]
        public string VanTay3 { get; set; }

        [Required]
        [Display(Name = "Trạng thái")]
        public bool TrangThai { get; set; }

        [Column(TypeName = "datetime2")]
        [Display(Name = "Ngày tạo")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime NgayTao { get; set; }

        [Column(TypeName = "datetime2")]
        [DataType(DataType.DateTime)]
        [Display(Name = "Ngày cập nhật")]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime NgayCapNhat { get; set; }

        public virtual NguoiDung NguoiDung { get; set; }
    }
}

DiemDanhVanTay/DiemDanhVanTay/Controllers/TheTuController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DiemDanhVanTay.DAO;
using DiemDanhVanTay.Models;

namespace DiemDanhVanTay.Controllers
{
    public class TheTuController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();

        // GET: TheTu
        public ActionResult Index()
        {
            ViewBag.NguoiDungID = new SelectList(unitOfWork.NguoiDungRepository.Get(), "NguoiDungID", "MSSV");
            var theTus = unitOfWork.TheTuRepository.Get(includeProperties: "NguoiDung");
            CreateAndIndexTheTuModel model = new CreateAndIndexTheTuModel();
            TheTu theTu = new TheTu();
            model.TheTus = theTus.ToList();
            model.TheTu = theTu;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index([Bind(Include = "NguoiDungID, TrangThai")] TheTu theTu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    theTu.NgayTao = DateTime.Now;
                    theTu.NgayCapNhat = DateTime.Now;
                    unitOfWork.TheTuRepository.Insert(theTu);
                    unitOfWork.Save();
                    ViewBag.InsertError = 0;
                    return RedirectToAction("Index");
                }        
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }

            ViewBag.InsertError = 1;
            ViewBag.NguoiDungID = new SelectList(unitOfWork.NguoiDungRepository.Get(), "NguoiDungID", "MSSV", theTu.NguoiDungID);
            var theTus = unitOfWork.TheTuRepository.Get(includeProperties: "NguoiDung");
            CreateAndIndexTheTuModel model = new CreateAndIndexTheTuModel();
            model.TheTus = theTus.ToList();
            model.TheTu = theTu;
            return View(model);
        }

        // GET: TheTu/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheTu theTu = unitOfWork.TheTuRepository.GetByID(id);
            if (theTu == null)
            {
                return HttpNotFound();
            }
            return View(theTu);
        }

        // GET: TheTu/Create
        public ActionResult Create()
        {
            ViewBag.NguoiDungID = new SelectList(unitOfWork.NguoiDungRepository.Get(), "NguoiDungID", "MSSV");
            return View();
        }

        // POST: TheTu/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TheTuID,NguoiDungID,VanTay1,VanTay2,VanTay3,TrangThai,NgayTao,NgayCapNhat")] TheTu theTu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    theTu.NgayTao = DateTime.Now;
                    theTu.NgayCapNhat = DateTime.Now;
                    unitOfWork.TheTuRepository.Insert(theTu);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }         
            ViewBag.NguoiDungID = new SelectList(unitOfWork.NguoiDungRepository.Get(), "NguoiDungID", "MSSV", theTu.NguoiDungID);
            return View(theTu);
        }

        // GET: TheTu/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheTu theTu = unitOfWork.TheTuRepository.GetByID(id);
            if (theTu == null)
            {
                return HttpNotFound();
            }
            ViewBag.NguoiDungID = new SelectList(unitOfWork.NguoiDungRepository.Get(), "NguoiDungID", "MSSV", theTu.NguoiDungID);
            return View(theTu);
        }

        // POST: TheTu/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TheTuID,NguoiDungID,VanTay1,VanTay2,VanTay3,TrangThai,NgayTao")] TheTu theTu)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    theTu.NgayCapNhat = DateTime.Now;
                    unitOfWork.TheTuRepository.Update(theTu);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
            }            
            ViewBag.NguoiDungID = new SelectList(unitOfWork.NguoiDungRepository.Get(), "NguoiDungID", "MSSV", theTu.NguoiDungID);
            return View(theTu);
        }

        // GET: TheTu/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TheTu theTu = unitOfWork.TheTuRepository.GetByID(id);
            if (theTu == null)
            {
                return HttpNotFound();
            }
            return View(theTu);
        }

        // POST: TheTu/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                TheTu theTu = unitOfWork.TheTuRepository.GetByID(id);
                unitOfWork.TheTuRepository.Delete(theTu);
                unitOfWork.Save();
                return RedirectToAction("Index");
            }
            catch (DataException /* dex */)
            {
                //Log the error (uncomment dex variable name after DataException and add a line here to write a log.
                return RedirectToAction("Delete", new { id = id, saveChangesError = true });
            }          
        }

        protected override void Dispose(bool disposing)
        {
            unitOfWork.Save();
            base.Dispose(disposing);
        }
    }
}

DiemDanhVanTay/DiemDanhVanTay/Controllers/TheTusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Description;
using DiemDanhVanTay.DAO;
using DiemDanhVanTay.Models;

namespace DiemDanhVanTay.Controllers
{
    public class TheTusController : ApiController
    {
        private DiemDanhDbContext db = new DiemDanhDbContext();

        // GET: api/TheTus
        [HttpGet]
        [Route("api/TheTus/getthetu")]
        public HttpResponseMessage Getnguoidung()
        {
            //db.TheTus
            //System.Collections.ArrayList returnInfo = new System.Collections.ArrayList();
            var infothetu = db.TheTus.Select( x => new {x.NguoiDung.HoTen, x.NguoiDung.LoaiNguoiDung.TenLoaiNguoiDung ,x.VanTay1} )
                .ToList();
            var res = Request.CreateResponse(HttpStatusCode.OK, infothetu );
            res.Headers.Add("Access-Control-Allow-Origin", "*");
            return res;
        }

        // GET: api/TheTus/5
        [ResponseType(typeof(TheTu))]
        public IHttpActionResult GetTheTu(int id)
        {
            TheTu theTu = db.TheTus.Find(id);
            if (theTu == null)
            {
                return NotFound();
            }

            return Ok(theTu);
        }

        // PUT: api/TheTus/5
        [ResponseType(typeof(void))]
        public IHttpActionResult PutTheTu(int id, TheTu theTu)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != theTu.TheTuID)
            {
                return BadRequest();
            }

            db.Entry(theTu).State = EntityState.Modified;

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TheTuExists(id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return StatusCode(HttpStatusCode.NoContent);
        }

        // POST: api/TheTus
        [ResponseType(typeof(TheTu))]
        public IHttpActionResult PostTheTu(TheTu theTu)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.TheTus.Add(theTu);
            db.SaveChanges();

            return CreatedAtRoute("DefaultApi", new { id = theTu.TheTuID }, theTu);
        }

        // DELETE: api/TheTus/5
        [ResponseType(typeof(TheTu))]
        public IHttpActionResult DeleteTheTu(int id)
        {
            TheTu theTu = db.TheTus.Find(id);
            if (theTu == null)
            {
                return NotFound();
            }

            db.TheTus.Remove(theTu);
            db.SaveChanges();

            return Ok(theTu);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool TheTuExists(int id)
        {
            return db.TheTus.Count(e => e.TheTuID == id) > 0;
        }
    }
}

DiemDanhVanTay/DiemDanhVanTay/Views/TheTu/Create.cshtml
@model DiemDanhVanTay.Models.TheTu

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TheTu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NguoiDungID, "NguoiDungID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NguoiDungID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NguoiDungID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VanTay1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VanTay1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VanTay1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VanTay2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VanTay2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VanTay2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VanTay3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VanTay3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VanTay3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = DateTime.Now } })
                @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = DateTime.Now } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DiemDanhVanTay/DiemDanhVanTay/Views/TheTu/Delete.cshtml
@model DiemDanhVanTay.Models.TheTu

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TheTu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NguoiDung.MSSV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDung.MSSV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VanTay1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VanTay1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VanTay2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VanTay2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VanTay3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VanTay3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DiemDanhVanTay/DiemDanhVanTay/Views/TheTu/Details.cshtml
@model DiemDanhVanTay.Models.TheTu

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TheTu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NguoiDung.MSSV)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiDung.MSSV)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VanTay1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VanTay1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VanTay2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VanTay2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VanTay3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VanTay3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TrangThai)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayTao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayTao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NgayCapNhat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NgayCapNhat)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.TheTuID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DiemDanhVanTay/DiemDanhVanTay/Views/TheTu/Edit.cshtml
@model DiemDanhVanTay.Models.TheTu

@{
    Layout = "~/Views/Shared/_MainLayout.cshtml";
    ViewBag.Title = "Cập nhật";
}

@*<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TheTu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TheTuID)

        <div class="form-group">
            @Html.LabelFor(model => model.NguoiDungID, "NguoiDungID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("NguoiDungID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NguoiDungID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VanTay1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VanTay1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VanTay1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VanTay2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VanTay2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VanTay2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VanTay3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VanTay3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VanTay3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TrangThai, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TrangThai, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayTao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayTao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = Convert.ToDateTime(Model.NgayTao) } })
                @Html.ValidationMessageFor(model => model.NgayTao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NgayCapNhat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NgayCapNhat, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", @Value = Convert.ToDateTime(Model.NgayCapNhat) } })
                @Html.ValidationMessageFor(model => model.NgayCapNhat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}*@

<!-- Content Header (Page header) -->
<section class="content-header">
    <h1>
        Cập nhật thẻ từ
    </h1>
    <ol class="breadcrumb">
        <li>
            <a href="@Url.Action("Index","Home")">
                <i class="fa fa-dashboard"></i> Trang chủ
            </a>
        </li>
        <li>
            <a href="@Url.Action("Index", "TheTu")">Thẻ từ</a>
        </li>
        <li class="active">Cập nhật</li>
    </ol>
</section>

<!-- Main content -->
<section class="content">
    <div class="row">
        <!-- left column -->
        <div class="col-md-offset-3 col-md-6">
            <!-- general form elements -->
            <div class="box box-primary mt-20">
                <div class="box-header with-border">
                    <h3 class="box-title">Cập nhật</h3>
                </div>
                <!-- /.box-header -->
                <!-- form start -->
                @*<form role="form">*@
                @using (Html.BeginForm())
                {
                    @Html.AntiForgeryToken()
                    <div class="box-body">
                        <div class="form-group">
                            <label>Mã thẻ</label>
                            @*<input type="text" class="form-control" placeholder="Tên người dùng...">*@
                           @* @Html.EditorFor(model => model.HoTen, new { htmlAttributes = new { @class = "form-control", @placeholder = "Tên người dùng..." } })*@
                            @Html.TextBoxFor(model => model.TheTuID, new { @class = "form-control", @readonly = "readonly" })
                        </div>
                        <div>
                            @Html.HiddenFor(model => model.TheTuID)
                            @Html.HiddenFor(model => model.NguoiDungID)
                            @Html.HiddenFor(model => model.VanTay1)
                            @Html.HiddenFor(model => model.VanTay2)
                            @Html.HiddenFor(model => model.VanTay3)
                            @Html.HiddenFor(model => model.NgayTao)
                        </div>
                        <div class="checkbox">
                            <label>
                                @*<input type="checkbox" checked> Kích hoạt tài khoản*@
                                @Html.EditorFor(model => model.TrangThai) Kích hoạt thẻ từ
                            </label>
                        </div>
                    </div>
                    <!-- /.box-body -->

                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">Lưu</button>
                    </div>
                }
                @*</form>*@
            </div>
            <!-- /.box -->
        </div>
        <!--/.col (left) -->
    </div>
    <!-- /.row -->
</section>